### ISSUE TITLE
Better msg when compilation fails to import something

### ISSUE THREAD

**Issue by LeonardoEichs** [nullstack/nullstack#177]
After `npm install` and `npm start` I got the following error:

```
 /Users/leonardoeichstaedt/Documents/Programming/space-game/overlay/node_modules/nullstack/scripts/index.js:24
  if (stats.hasErrors()) {
            ^
TypeError: Cannot read properties of undefined (reading 'hasErrors')
    at logTrace (/Users/leonardoeichstaedt/Documents/Programming/space-game/overlay/node_modules/nullstack/scripts/index.js:24:13)
    at /Users/leonardoeichstaedt/Documents/Programming/space-game/overlay/node_modules/nullstack/scripts/index.js:55:40
    at Watching.handler (/Users/leonardoeichstaedt/Documents/Programming/space-game/overlay/node_modules/webpack/lib/MultiCompiler.js:215:17)
    at Watching._done (/Users/leonardoeichstaedt/Documents/Programming/space-game/overlay/node_modules/webpack/lib/Watching.js:95:9)
    at /Users/leonardoeichstaedt/Documents/Programming/space-game/overlay/node_modules/webpack/lib/Watching.js:52:27
    at /Users/leonardoeichstaedt/Documents/Programming/space-game/overlay/node_modules/webpack/lib/Compiler.js:480:22
    at /Users/leonardoeichstaedt/Documents/Programming/space-game/overlay/node_modules/neo-async/async.js:2830:7
    at done (/Users/leonardoeichstaedt/Documents/Programming/space-game/overlay/node_modules/neo-async/async.js:3517:9)
    at /Users/leonardoeichstaedt/Documents/Programming/space-game/overlay/node_modules/webpack/lib/Compiler.js:463:25
    at node:fs:2122:7
```

Apparently something failed to be downloaded on `npm install`

Solution was to clone repository again and use yarn

**Comment by Mortaro** [comment]
Thanks! fixed 💜
