### ISSUE TITLE
Module build fail sometimes [Unstable Next]

### ISSUE THREAD

**Issue by jayremias** [nullstack/nullstack#254]
```
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Unsupported operation: 'Uri.base' is not supported
```
this errors happens sometimes, seens to be related with the browser still opens trying to connect to socket.

Complete error information [tailwind included]

```
Compiled with problems:

ERROR in ./src/tailwind.css (./src/tailwind.css.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[7].use[1]!./node_modules/sass-loader/dist/cjs.js!./src/tailwind.css)

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Unsupported operation: 'Uri.base' is not supported


ERROR in ./src/tailwind.css

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Unsupported operation: 'Uri.base' is not supported
    at tryRunOrWebpackError (/home/jay/dev/aeskills/node_modules/webpack/lib/HookWebpackError.js:88:9)
    at __webpack_require_module__ (/home/jay/dev/aeskills/node_modules/webpack/lib/Compilation.js:5051:12)
    at __webpack_require__ (/home/jay/dev/aeskills/node_modules/webpack/lib/Compilation.js:5008:18)
    at /home/jay/dev/aeskills/node_modules/webpack/lib/Compilation.js:5079:20
    at symbolIterator (/home/jay/dev/aeskills/node_modules/neo-async/async.js:3485:9)
    at done (/home/jay/dev/aeskills/node_modules/neo-async/async.js:3527:9)
    at Hook.eval [as callAsync] (eval at create (/home/jay/dev/aeskills/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/jay/dev/aeskills/node_modules/webpack/lib/Compilation.js:4986:43
    at symbolIterator (/home/jay/dev/aeskills/node_modules/neo-async/async.js:3482:9)
    at timesSync (/home/jay/dev/aeskills/node_modules/neo-async/async.js:2297:7)
```

**Comment by Mortaro** [comment]
fixed in 0.16.0
