### ISSUE TITLE
M1 - postcss loader breaks

### ISSUE THREAD

**Issue by robgetTheJobDoneSP** [nullstack/nullstack#322]
On the m1 mac,  with tailwind installed when you make changes to class after awhile the compiler breaks. 

`ERROR in ./tailwind.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
RangeError: Maximum call stack size exceeded
    at String.match (<anonymous>)
    at /Users/robertseares/planetplay-webplatform/node_modules/tailwindcss/lib/lib/defaultExtractor.js:60:35
    at getClassCandidates (/Users/robertseares/planetplay-webplatform/node_modules/tailwindcss/lib/lib/expandTailwindAtRules.js:96:36)
    at /Users/robertseares/planetplay-webplatform/node_modules/tailwindcss/lib/lib/expandTailwindAtRules.js:155:13
    at /Users/robertseares/planetplay-webplatform/node_modules/tailwindcss/lib/processTailwindFeatures.js:51:53
    at plugins (/Users/robertseares/planetplay-webplatform/node_modules/tailwindcss/lib/index.js:38:63)
    at LazyResult.runOnRoot (/Users/robertseares/planetplay-webplatform/node_modules/postcss/lib/lazy-result.js:339:16)
    at LazyResult.runAsync (/Users/robertseares/planetplay-webplatform/node_modules/postcss/lib/lazy-result.js:393:26)
    at LazyResult.async (/Users/robertseares/planetplay-webplatform/node_modules/postcss/lib/lazy-result.js:221:30)
    at LazyResult.then (/Users/robertseares/planetplay-webplatform/node_modules/postcss/lib/lazy-result.js:206:17)
    at tryRunOrWebpackError (/Users/robertseares/planetplay-webplatform/node_modules/nullstack/node_modules/webpack/lib/HookWebpackError.js:88:9)
    at __webpack_require_module__ (/Users/robertseares/planetplay-webplatform/node_modules/nullstack/node_modules/webpack/lib/Compilation.js:5051:12)
    at __webpack_require__ (/Users/robertseares/planetplay-webplatform/node_modules/nullstack/node_modules/webpack/lib/Compilation.js:5008:18)
    at /Users/robertseares/planetplay-webplatform/node_modules/nullstack/node_modules/webpack/lib/Compilation.js:5079:20
    at symbolIterator (/Users/robertseares/planetplay-webplatform/node_modules/neo-async/async.js:3485:9)
    at done (/Users/robertseares/planetplay-webplatform/node_modules/neo-async/async.js:3527:9)
    at Hook.eval [as callAsync] (eval at create (/Users/robertseares/planetplay-webplatform/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/robertseares/planetplay-webplatform/node_modules/nullstack/node_modules/webpack/lib/Compilation.js:4986:43
    at symbolIterator (/Users/robertseares/planetplay-webplatform/node_modules/neo-async/async.js:3482:9)
    at timesSync (/Users/robertseares/planetplay-webplatform/node_modules/neo-async/async.js:2297:7)
-- inner error --
Error: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
RangeError: Maximum call stack size exceeded
    at String.match (<anonymous>)
    at /Users/robertseares/planetplay-webplatform/node_modules/tailwindcss/lib/lib/defaultExtractor.js:60:35
    at getClassCandidates (/Users/robertseares/planetplay-webplatform/node_modules/tailwindcss/lib/lib/expandTailwindAtRules.js:96:36)
    at /Users/robertseares/planetplay-webplatform/node_modules/tailwindcss/lib/lib/expandTailwindAtRules.js:155:13
    at /Users/robertseares/planetplay-webplatform/node_modules/tailwindcss/lib/processTailwindFeatures.js:51:53
    at plugins (/Users/robertseares/planetplay-webplatform/node_modules/tailwindcss/lib/index.js:38:63)
    at LazyResult.runOnRoot (/Users/robertseares/planetplay-webplatform/node_modules/postcss/lib/lazy-result.js:339:16)
    at LazyResult.runAsync (/Users/robertseares/planetplay-webplatform/node_modules/postcss/lib/lazy-result.js:393:26)
    at LazyResult.async (/Users/robertseares/planetplay-webplatform/node_modules/postcss/lib/lazy-result.js:221:30)
    at LazyResult.then (/Users/robertseares/planetplay-webplatform/node_modules/postcss/lib/lazy-result.js:206:17)
    at Object.<anonymous> (/Users/robertseares/planetplay-webplatform/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[7].use[1]!/Users/robertseares/planetplay-webplatform/node_modules/sass-loader/dist/cjs.js!/Users/robertseares/planetplay-webplatform/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[7].use[3]!/Users/robertseares/planetplay-webplatform/tailwind.css:1:7)
    at /Users/robertseares/planetplay-webplatform/node_modules/nullstack/node_modules/webpack/lib/javascript/JavascriptModulesPlugin.js:441:11
    at Hook.eval [as call] (eval at create (/Users/robertseares/planetplay-webplatform/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at /Users/robertseares/planetplay-webplatform/node_modules/nullstack/node_modules/webpack/lib/Compilation.js:5053:39
    at tryRunOrWebpackError (/Users/robertseares/planetplay-webplatform/node_modules/nullstack/node_modules/webpack/lib/HookWebpackError.js:83:7)
    at __webpack_require_module__ (/Users/robertseares/planetplay-webplatform/node_modules/nullstack/node_modules/webpack/lib/Compilation.js:5051:12)
    at __webpack_require__ (/Users/robertseares/planetplay-webplatform/node_modules/nullstack/node_modules/webpack/lib/Compilation.js:5008:18)
    at /Users/robertseares/planetplay-webplatform/node_modules/nullstack/node_modules/webpack/lib/Compilation.js:5079:20
    at symbolIterator (/Users/robertseares/planetplay-webplatform/node_modules/neo-async/async.js:3485:9)
    at done (/Users/robertseares/planetplay-webplatform/node_modules/neo-async/async.js:3527:9)

Generated code for /Users/robertseares/planetplay-webplatform/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[7].use[1]!/Users/robertseares/planetplay-webplatform/node_modules/sass-loader/dist/cjs.js!/Users/robertseares/planetplay-webplatform/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[7].use[3]!/Users/robertseares/planetplay-webplatform/tailwind.css
1 | throw new Error("Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):\nRangeError: Maximum call stack size exceeded\n    at String.match (<anonymous>)\n    at /Users/robertseares/planetplay-webplatform/node_modules/tailwindcss/lib/lib/defaultExtractor.js:60:35\n    at getClassCandidates (/Users/robertseares/planetplay-webplatform/node_modules/tailwindcss/lib/lib/expandTailwindAtRules.js:96:36)\n    at /Users/robertseares/planetplay-webplatform/node_modules/tailwindcss/lib/lib/expandTailwindAtRules.js:155:13\n    at /Users/robertseares/planetplay-webplatform/node_modules/tailwindcss/lib/processTailwindFeatures.js:51:53\n    at plugins (/Users/robertseares/planetplay-webplatform/node_modules/tailwindcss/lib/index.js:38:63)\n    at LazyResult.runOnRoot (/Users/robertseares/planetplay-webplatform/node_modules/postcss/lib/lazy-result.js:339:16)\n    at LazyResult.runAsync (/Users/robertseares/planetplay-webplatform/node_modules/postcss/lib/lazy-result.js:393:26)\n    at LazyResult.async (/Users/robertseares/planetplay-webplatform/node_modules/postcss/lib/lazy-result.js:221:30)\n    at LazyResult.then (/Users/robertseares/planetplay-webplatform/node_modules/postcss/lib/lazy-result.js:206:17)");
 @ ./src/Application.jsx 64:0-25
 @ ./client.js 6:0-44 11:32-43 86:45-88:7 87:28-39 86:6-88:8`

"postcss": "^8.4.19",
"postcss-loader": "^7.0.1",
"tailwind-merge": "^1.4.0",
"tailwindcss": "^3.2.4"

**Comment by alissonsuassuna** [comment]
vou está analisando

**Comment by robgetTheJobDoneSP** [comment]
In the mean time if anyone has issues you can use this script to auto restart it 


`const { spawn } = require('child_process')
let child
const startScript = () => {
  child = spawn('npm', ['run', 'start'])
  child.stdout.on('data', (data) => {
    console.log(`stdout: ${data}`)
    if (data.includes('error')) {
      child.kill()
      startScript()
    }
  })
  child.stderr.on('data', (data) => {
    console.error(`stderr: ${data}`)
    child.kill()
    startScript()
  })
  child.on('close', (code) => {
    console.log(`child process exited with code ${code}`)
  })
}
startScript()`

**Comment by robgetTheJobDoneSP** [comment]
Also full dependencies


`  "dependencies": {
    "@analytics/google-tag-manager": "^0.5.2",
    "@auth0/auth0-spa-js": "^1.22.2",
    "@faker-js/faker": "^7.3.0",
    "@sentry/browser": "^7.28.0",
    "@sentry/integrations": "^7.28.1",
    "@sentry/tracing": "^7.28.0",
    "@stripe/stripe-js": "^1.38.1",
    "@tailwindcss/line-clamp": "^0.4.2",
    "@tailwindcss/typography": "^0.5.8",
    "analytics": "^0.8.1",
    "aws-sdk": "^2.1248.0",
    "browser-image-resizer": "^2.4.1",
    "buffer": "^6.0.3",
    "canvas": "^2.10.2",
    "chart.js": "^3.9.1",
    "cors": "^2.8.5",
    "currency-codes": "^2.1.0",
    "currency-symbol-map": "^5.1.0",
    "dayjs": "^1.11.4",
    "jsonwebtoken": "^8.5.1",
    "jwt-decode": "^3.1.2",
    "papaparse": "^5.3.2",
    "stripe": "^10.13.0",
    "timers": "^0.1.1",
    "xml2js": "^0.4.23"
  },
  "devDependencies": {
    "@sentry/webpack-plugin": "^1.20.0",
    "@tailwindcss/forms": "^0.5.3",
    "@trivago/prettier-plugin-sort-imports": "^3.4.0",
    "autoprefixer": "^10.4.13",
    "cypress": "^10.11.0",
    "eslint": "^8.20.0",
    "eslint-plugin-local": "^1.0.0",
    "husky": "^8.0.1",
    "lint-staged": "^13.0.3",
    "nullstack": "^0.16.4",
    "postcss": "^8.4.19",
    "postcss-loader": "^7.0.1",
    "prettier": "^2.7.1",
    "prettier-plugin-tailwindcss": "^0.1.12",
    "query-string": "^7.1.1",
    "tailwind-merge": "^1.4.0",
    "tailwindcss": "^3.2.4"
  },`

**Comment by Mortaro** [comment]
Closing for now as it seems to be a tailwind related thing and not nullstack, but it might disappear anyway in the next version with the new loaders. Pls, reopen if it happens again!
